
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cegafrwmqkhqtlyvbwob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlZ2FmcndtcWtocXRseXZid29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDE3MTgsImV4cCI6MjA2NTIxNzcxOH0.bJ-7zn4ndmJnfbdIcyfw4mqnm5hPaEbou0P0OQeVB_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
